name: CI

on: [push, workflow_dispatch]

jobs:

build:

runs-on: windows-latest

steps:

- name: Download

run: Invoke-WebRequest

https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-wi

ndows-amd64.zip -Out File ngrok.zip

- name: Extract

run: Expand-Archive ngrok.zip

- name: Auth

run: .\ngrok\ngrok.exe authtoken
